# Generated by Django 4.2.11 on 2024-04-24 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='futsal_court',
            fields=[
                ('futsal_court_id', models.AutoField(primary_key=True, serialize=False)),
                ('futsal_name', models.CharField(max_length=50)),
                ('futsal_court_phone', models.CharField(max_length=10)),
                ('futsal_court_address', models.CharField(max_length=50)),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('user_phone', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='boooking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('duration', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
    ]
