# Generated by Django 5.0.6 on 2024-07-31 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_futsal_court_futsal_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='futsal_court',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.futsal_court'),
        ),
    ]
